# Generated by Django 4.2.2 on 2023-11-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='prenom',
        ),
    ]
