# Generated by Django 4.2.2 on 2023-11-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0002_remove_adresse_nom_remove_adresse_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('en cours de traitement', 'En cours de traitement'), ('expédiée', 'Expédiée'), ('livrée', 'Livrée'), ('annulée', 'Annulée')], max_length=255),
        ),
    ]
