# Generated by Django 4.2.2 on 2023-11-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0003_alter_commande_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='montant',
        ),
    ]
