# Generated by Django 4.2.2 on 2023-11-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0004_remove_commande_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='montant',
            field=models.FloatField(default=0),
        ),
    ]
